[package]
name = "mw-cas"
version = "0.1.0"
authors = ["Dmitriy <d.razumovskiy@kupibilet.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.4.1"
